import{Router}from"express";import multer from"multer";import{protect}from"../middleware/auth.js";import{login}from"../controllers/auth.js";import*as C from"../controllers/crud.js";import*as E from"../controllers/enquiry.js";import*as D from"../controllers/dashboard.js";import{pub as publicSettings,get as getSettings,save as saveSettings}from"../controllers/settings.js";import{uploadImage}from"../controllers/upload.js";
const r=Router(),u=["services","projects","technologies"];r.post("/auth/admin/login",login);
u.forEach(t=>{r.get(`/${t}/public`,(q,s)=>{q.params.type=t;return C.pub(q,s)});r.get(`/${t}`,protect,(q,s)=>{q.params.type=t;return C.list(q,s)});r.post(`/${t}`,protect,(q,s)=>{q.params.type=t;return C.save(q,s)});r.put(`/${t}/:id`,protect,(q,s)=>{q.params.type=t;return C.save(q,s)});r.delete(`/${t}/:id`,protect,(q,s)=>{q.params.type=t;return C.del(q,s)})});
r.post("/enquiries",E.create);r.get("/enquiries",protect,E.list);r.patch("/enquiries/:id",protect,E.update);r.delete("/enquiries/:id",protect,E.del);
r.post("/dashboard/view",D.view);r.get("/dashboard",protect,D.dashboard);
r.get("/settings/public",publicSettings);r.get("/settings",protect,getSettings);r.put("/settings",protect,saveSettings);
const IMAGE_TYPES=["image/jpeg","image/jpg","image/png","image/webp"],MAX_IMAGE_BYTES=8*1024*1024;
const imageUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_IMAGE_BYTES},fileFilter:(q,f,cb)=>IMAGE_TYPES.includes(f.mimetype)?cb(null,true):cb(Object.assign(new Error("Unsupported file. Please choose a JPG, JPEG, PNG or WEBP image."),{statusCode:422}))});
const singleImage=(q,s,n)=>imageUpload.single("image")(q,s,e=>{if(!e)return n();if(e.code==="LIMIT_FILE_SIZE")return s.status(413).json({message:"Image is too large. Maximum size is 8 MB."});return s.status(e.statusCode||422).json({message:e.message||"Unsupported image file."})});
r.post("/uploads/image",protect,singleImage,uploadImage);
export default r;