import mongoose from "mongoose";

const list = { type: [mongoose.Schema.Types.Mixed], default: undefined };
const settingsSchema = new mongoose.Schema({
  siteTitle: String,
  logoUrl: String,
  faviconUrl: String,
  brandPrimaryText: String,
  brandSecondaryText: String,
  navbarItems: list,
  navbarCtaText: String,
  navbarCtaRouteKey: String,
  navbarCtaVisible: { type: Boolean, default: true },
  footerLogoUrl: String,
  footerDescription: String,
  footerQuickLinksHeading: String,
  footerQuickLinks: list,
  footerServicesHeading: String,
  footerServiceLinks: list,
  footerContactHeading: String,
  footerPhone: String,
  footerEmail: String,
  footerWhatsapp: String,
  footerLocation: String,
  footerSocialLinks: [String],
  footerBrandVisible: { type: Boolean, default: true },
  footerQuickLinksVisible: { type: Boolean, default: true },
  footerServicesVisible: { type: Boolean, default: true },
  footerContactVisible: { type: Boolean, default: true },
  footerSocialVisible: { type: Boolean, default: true },
  footerCopyrightText: String,
  footerTagline: String,
  footerPrivacyLabel: String,
  footerTermsLabel: String,
  footerWhatsappLabel: String,
  footerShowPhone: { type: Boolean, default: true },
  footerShowEmail: { type: Boolean, default: true },
  footerShowWhatsapp: { type: Boolean, default: true },
  footerShowLocation: { type: Boolean, default: true },

  heroImageUrl: String,
  homeHeroEyebrow: String,
  homeHeroTitle: String,
  homeHeroSecondaryTitle: String,
  homeHeroThirdTitle: String,
  homeHeroSubtitle: String,
  homeHeroDescription: String,
  homeHeroCtaText: String,
  homeHeroCtaUrl: String,
  homeHeroCtaRouteKey: String,
  heroVisible: { type: Boolean, default: true },
  heroCtaVisible: { type: Boolean, default: true },
  homeHeroVerticalWords: list,
  homeHeroVerticalVisible: { type: Boolean, default: true },
  homeAboutEyebrow: String,
  homeAboutTitle: String,
  homeAboutDescription: String,
  homeAboutCtaText: String,
  homeAboutCtaRouteKey: String,
  aboutVisible: { type: Boolean, default: true },
  servicesVisible: { type: Boolean, default: true },
  projectsVisible: { type: Boolean, default: true },
  technologiesVisible: { type: Boolean, default: true },
  whyVisible: { type: Boolean, default: true },
  processVisible: { type: Boolean, default: true },
  faqVisible: { type: Boolean, default: true },
  testimonialsVisible: { type: Boolean, default: true },
  finalCtaVisible: { type: Boolean, default: true },
  homeServicesEyebrow: String,
  homeServicesTitle: String,
  homeServicesDescription: String,
  homeServicesCtaText: String,
  homeServicesCtaRouteKey: String,
  homeProjectsEyebrow: String,
  homeProjectsTitle: String,
  homeProjectsDescription: String,
  homeProjectsCtaText: String,
  homeProjectsCtaRouteKey: String,
  homeTechnologiesEyebrow: String,
  homeTechnologiesTitle: String,
  homeTechnologiesDescription: String,
  homeWhyEyebrow: String,
  whyItems: list,
  whyTitle: String,
  whyDescription: String,
  processSteps: list,
  processTitle: String,
  processDescription: String,
  processEyebrow: String,
  processPageVisible: { type: Boolean, default: true },
  processCtaText: String,
  processCtaRouteKey: String,
  faqItems: list,
  homeFaqEyebrow: String,
  homeFaqTitle: String,
  homeFaqDescription: String,
  homeTestimonialsEyebrow: String,
  homeTestimonialsTitle: String,
  homeTestimonialsDescription: String,
  testimonials: list,
  finalCtaTitle: String,
  finalCtaEyebrow: String,
  finalCtaDescription: String,
  finalCtaButtonText: String,
  finalCtaButtonRouteKey: String,
  finalCtaWhatsappText: String,

  aboutImageUrl: String,
  aboutPageVisible: { type: Boolean, default: true },
  aboutEyebrow: String,
  aboutTitle: String,
  aboutDescription: String,
  aboutPrimaryCtaText: String,
  aboutPrimaryCtaRouteKey: String,
  aboutSecondaryCtaText: String,
  aboutSecondaryCtaRouteKey: String,
  aboutTechVisible: { type: Boolean, default: true },
  aboutTechEyebrow: String,
  aboutTechTitle: String,
  aboutTechDescription: String,
  aboutHighlights: list,

  servicesPageEyebrow: String,
  servicesPageVisible: { type: Boolean, default: true },
  servicesPageTitle: String,
  servicesPageDescription: String,
  servicesCtaText: String,
  servicesCtaRouteKey: String,
  serviceCardCtaText: String,
  serviceCardCtaRouteKey: String,
  portfolioPageEyebrow: String,
  portfolioPageVisible: { type: Boolean, default: true },
  portfolioPageTitle: String,
  portfolioPageDescription: String,
  projectDemoLabel: String,
  projectGithubLabel: String,
  projectDetailsLabel: String,
  technologiesPageEyebrow: String,
  technologiesPageVisible: { type: Boolean, default: true },
  technologiesPageTitle: String,
  technologiesPageDescription: String,

  contactEyebrow: String,
  contactPageVisible: { type: Boolean, default: true },
  contactTitle: String,
  contactDescription: String,
  contactPhoneLabel: String,
  contactEmailLabel: String,
  contactLocationLabel: String,
  contactWhatsappLabel: String,
  contactSocialLabel: String,
  contactNameLabel: String,
  contactNamePlaceholder: String,
  contactEmailFieldLabel: String,
  contactEmailPlaceholder: String,
  contactPhoneFieldLabel: String,
  contactCompanyLabel: String,
  contactCompanyPlaceholder: String,
  contactServiceLabel: String,
  contactOtherServiceLabel: String,
  contactServicePlaceholder: String,
  contactBudgetLabel: String,
  contactOptionalLabel: String,
  contactBudgetPlaceholder: String,
  contactPhonePlaceholder: String,
  contactMessageLabel: String,
  contactMessagePlaceholder: String,
  contactSubmitLabel: String,
  contactSendingLabel: String,
  contactSuccessMessage: String,
  contactWhatsappUrl: String,
  phone: String,
  whatsapp: String,
  email: String,
  location: String,
  socialLinks: [String],

  privacyTitle: String,
  privacyEyebrow: String,
  privacyIntro: String,
  privacySections: list,
  termsTitle: String,
  termsEyebrow: String,
  termsIntro: String,
  termsSections: list,

  seoTitle: String,
  seoDescription: String,
  ogTitle: String,
  ogDescription: String,
  ogImage: String,
  pageSeo: list,
}, { timestamps: true });

export default mongoose.model("Settings", settingsSchema);
